--- 
- 
  name: "Add epel-release repo"
  yum: 
    name: epel-release
    state: present
- 
  become: true
  name: "install nginx"
  yum: 
    name: 
      - nginx
    state: present
    update_cache: true
- 
  become: true
  name: "start nginx"
  service: 
    name: nginx
    state: started
- 
  name: index
  template: 
    dest: /var/www/html/index.html
    src: index.html.j2

